services:
  postgres:
    env_file: .env
    image: postgres:latest
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      PGTZ: ${TIMEZONE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 5s
#  mysql:
#    env_file: .env
#    image: mysql:latest
#    container_name: mysql_test
#    restart: always
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "${MYSQL_PORT}:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_HOST}", "-u ${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
#      interval: 5s
#      retries: 5
#      timeout: 5s

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local
